yolo_model:

  config_file:
    name: LARC2023.cfg
  weight_file:
    name: LARC2023.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - Fruits/Apple
      - Fruits/Banana
      - Fruits/Banana Bunch
      - Snacks/Cereal Bag
      - Cleaning supplies/Cloth
      - Drinks/Coca-cola Bottle
      - Drinks/Coconut Water
      - Snacks/Cookies
      - Cleaning supplies/Detergent
      - Drinks/Guaraná Bottle
      - Drinks/Ice Tea
      - Fruits/Kiwi
      - Pantry items/Mustard
      - Fruits/Orange
      - Snacks/Potato Chips
      - Pantry items/Sardines
      - Cleaning supplies/Sponge
      - Pantry items/Tomato Sauce
      - Drinks/Tonic Water
      - Drinks/Water Bottle
      - Pantry items/Worcestershire Sauce
